let state={tournaments:[],divisions:[],teams:[],matches:[],audit:[]};
let players=[],posts=[],sponsors=[],branding={};
const $=s=>document.querySelector(s);
const isPreview=location.pathname.includes("/preview/");
const href=p=>isPreview?p.replace(/^\//,""):p;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const initials=name=>(name||"P").trim().split(/\s+/).slice(-2).map(x=>x[0]).join("").toUpperCase();
const team=id=>state.teams.find(t=>t.id===id)?.name||(id==="TBD"||!id?"Chưa xác định":id);
const score=(m,side)=>m.current?.[side==="a"?0:1]??0;
const badge=s=>s==="live"?'<span class="badge live">LIVE</span>':s==="done"?'<span class="badge done">KẾT THÚC</span>':s==="open"?'<span class="badge blue">ĐANG MỞ</span>':'<span class="badge wait">SẮP ĐẤU</span>';
const avatar=(p,cls="top-player-avatar")=>p.avatar_url?'<img class="'+cls+'" src="'+esc(p.avatar_url)+'" alt="'+esc(p.full_name)+'">':'<span class="'+cls+' avatar-fallback">'+esc(initials(p.full_name))+'</span>';
function liveCard(m){return '<div class="hero-score"><div class="hero-score-meta"><span>'+esc(m.stage||"Trận đấu")+'</span><span>Sân '+esc(m.court)+' • '+esc(m.time)+'</span></div><div class="line"><strong>'+esc(team(m.a))+'</strong><span class="points">'+score(m,"a")+'</span></div><div class="line"><strong>'+esc(team(m.b))+'</strong><span class="points">'+score(m,"b")+'</span></div></div>'}
function renderCore(){
 const live=state.matches.filter(m=>m.status==="live");
 if($("#liveCount"))$("#liveCount").textContent=live.length+" trận";
 if($("#mobileLiveCount"))$("#mobileLiveCount").textContent=live.length;
 if($("#heroLive"))$("#heroLive").innerHTML=live.slice(0,2).map(liveCard).join("")||'<div class="hero-score empty-live"><b>Chưa có trận live</b><span>Live Center sẽ cập nhật khi trận bắt đầu.</span></div>';
 if($("#publicTours"))$("#publicTours").innerHTML=state.tournaments.map(t=>{const featTag=t.isFeatured?`<span class="tour-featured-badge ${t.sponsorPackage==='top_sponsor'?'gold':''}">${t.sponsorPackage==='top_sponsor'?'⭐ ĐỈNH BẢNG':'★ NỔI BẬT'}</span>`:"";return '<a class="tour-card '+(t.isFeatured?'is-featured':'')+'" href="'+href('/tournament.html?id='+encodeURIComponent(t.id))+'" style="text-decoration:none;color:inherit"><div class="tour-media tour-media-real">'+featTag+'<div class="tour-pickle-art" aria-hidden="true"><i></i><b>🏓</b></div><div class="tour-media-shade"></div><div class="tour-cover"><div><small>TOURNAMENT</small><strong>'+esc(t.format||"Tournament")+'</strong></div>'+badge(t.status)+'</div></div><div class="tour-body"><h3>'+esc(t.name)+'</h3><div class="tour-meta-grid"><span><small>Ngày</small><b>'+esc(t.date)+'</b></span><span><small>Địa điểm</small><b>'+esc(t.venue)+'</b></span><span><small>Đội</small><b>'+esc(t.teams??0)+'</b></span></div></div></a>';}).join("")||'<div class="empty">Chưa có giải công khai.</div>';
 if($("#publicMatches"))$("#publicMatches").innerHTML=state.matches.filter(m=>m.status!=="done").slice(0,12).map(m=>'<article class="public-match"><div class="public-match-top"><span>'+esc(m.stage)+' • '+esc(m.time)+' • Sân '+esc(m.court)+'</span>'+badge(m.status)+'</div><div class="public-team-row"><b>'+esc(team(m.a))+'</b><b>'+(m.status==="live"?score(m,"a"):"—")+'</b></div><div class="public-team-row"><b>'+esc(team(m.b))+'</b><b>'+(m.status==="live"?score(m,"b"):"—")+'</b></div></article>').join("")||'<div class="empty">Chưa có trận.</div>';
 function sortGroupTeams(arr,matches){return [...arr].sort((a,b)=>{if(b.w!==a.w)return b.w-a.w;const sdA=(a.sw||0)-(a.sl||0),sdB=(b.sw||0)-(b.sl||0);if(sdB!==sdA)return sdB-sdA;if(matches&&matches.length){const h2h=matches.find(m=>(m.status==="done"||m.status==="completed")&&((m.a===a.id&&m.b===b.id)||(m.a===b.id&&m.b===a.id))&&m.winner);if(h2h){if(h2h.winner===a.id)return -1;if(h2h.winner===b.id)return 1;}}return ((b.pf-b.pa)-(a.pf-a.pa))||(b.pf-a.pf)||((a.seed||999)-(b.seed||999));});}
 const groups=[...new Set(state.teams.map(t=>t.group).filter(Boolean))];
 if($("#publicStandings"))$("#publicStandings").innerHTML=groups.map(g=>{const rows=sortGroupTeams(state.teams.filter(t=>t.group===g),state.matches);return '<div class="public-standings"><div class="panel-head"><div><span class="eyebrow">BẢNG '+esc(g)+'</span><h2>Xếp hạng Bảng '+esc(g)+'</h2></div><span class="badge blue">TOP 2 ĐI TIẾP</span></div><div class="standing-table-wrap"><div class="standing-row head"><span>#</span><span>Đội / VĐV</span><span>Trận</span><span>Set</span><span>Điểm</span><span>+/-</span><span>Xếp hạng</span></div>'+rows.map((t,i)=>{const rankTag=i===0?'<span class="rank-badge rank-1">🥇 Nhất bảng</span><small class="qualify-status">Vào vòng trong</small>':i===1?'<span class="rank-badge rank-2">🥈 Nhì bảng</span><small class="qualify-status">Vào vòng trong</small>':'<span class="rank-badge rank-other">Hạng '+(i+1)+'</span>';const qCls=i===0?'qualify-rank-1':i===1?'qualify-rank-2':'';const diff=t.pf-t.pa;return '<div class="standing-row '+qCls+'"><b>'+(i+1)+'</b><span><b>'+esc(t.name)+'</b><small class="muted-block">'+esc(t.club||"")+'</small></span><span>'+t.w+'-'+t.l+'</span><span>'+(t.sw||0)+'-'+(t.sl||0)+'</span><span>'+t.pf+'-'+t.pa+'</span><b>'+(diff>0?'+':'')+diff+'</b><div>'+rankTag+'</div></div>';}).join("")+'</div></div>'}).join("")||'<div class="empty">Chưa có bảng xếp hạng.</div>';
 if($("#publicBracket")){const html=window.PickleBracket?.render(state.matches,team,{admin:false})||'<div class="empty">Chưa có bracket.</div>';const champ=window.PickleBracket?.champion(state.matches,team);$("#publicBracket").innerHTML=html+(champ&&champ!=="Chưa xác định"?'<div class="public-champion"><span>CHAMPION</span><strong>'+esc(champ)+'</strong></div>':"")}
}
function renderPlayers(){const el=$("#publicTopPlayers");if(!el)return;const top=[...players].filter(p=>p.active!==false).sort((a,b)=>Number(b.rating||0)-Number(a.rating||0)).slice(0,6);el.innerHTML=top.map((p,i)=>'<a class="top-player-card" href="'+href('/player.html?id='+encodeURIComponent(p.id))+'"><div class="top-player-rank">0'+(i+1)+'</div>'+avatar(p)+'<div class="top-player-copy"><b>'+esc(p.full_name)+'</b><span>'+esc(p.club_name||"Tự do")+'</span></div><strong>'+Number(p.rating||0).toFixed(3)+'</strong></a>').join("")||'<div class="empty">Chưa có dữ liệu rating.</div>'}
function renderPosts(){const el=$("#publicNews");if(!el)return;el.innerHTML=posts.slice(0,6).map(p=>'<article class="news-card"><div class="news-card-body"><span class="eyebrow">UPDATE</span><h3>'+esc(p.title)+'</h3><p>'+esc(p.excerpt||"")+'</p><small>'+(p.published_at?new Date(p.published_at).toLocaleDateString("vi-VN"):"")+'</small></div></article>').join("")||'<div class="empty">Chưa có tin mới.</div>'}
function renderSponsors(){const el=$("#publicSponsors");if(!el)return;el.innerHTML=sponsors.map(s=>'<a class="public-sponsor" href="'+esc(s.website_url||"#")+'" '+(s.website_url?'target="_blank" rel="noopener noreferrer"':"")+'>'+(s.logo_url?'<img src="'+esc(s.logo_url)+'" alt="'+esc(s.name)+'">':'<b>'+esc(s.name)+'</b>')+'<span>'+esc(s.tier||"Partner")+'</span></a>').join("")||'<span class="sponsor-empty">Chưa có sponsor công khai.</span>'}
function applyBranding(){if(branding.primaryColor)document.documentElement.style.setProperty("--brand",branding.primaryColor);if(branding.accentColor)document.documentElement.style.setProperty("--acid",branding.accentColor);document.querySelectorAll(".public-brand b").forEach(el=>{if(branding.name)el.textContent=branding.name})}
async function load(){try{[state,players,posts,sponsors,branding]=await Promise.all([PickleAPI.publicState(),PickleAPI.publicPlayers().catch(()=>[]),PickleAPI.publicPosts().catch(()=>[]),PickleAPI.publicSponsors().catch(()=>[]),PickleAPI.publicBranding().catch(()=>({}))]);applyBranding();renderCore();renderPlayers();renderPosts();renderSponsors()}catch(e){console.error(e)}}
load();if(window.io){const socket=io();socket.on("public:state",s=>{state=s;renderCore()})}