(()=>{
  const KEY="pickle-local-state-v1";
  const uid=()=>crypto.randomUUID?.()||("id-"+Date.now()+"-"+Math.random().toString(16).slice(2));
  const clone=x=>JSON.parse(JSON.stringify(x));
  const svgAvatar=(name,bg="#0d2118",fg="#dfff69")=>{
    const ini=(name||"P").split(/\s+/).slice(-2).map(x=>x[0]).join("").toUpperCase();
    const svg='<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" rx="72" fill="'+bg+'"/><circle cx="196" cy="60" r="46" fill="#ffffff12"/><text x="128" y="148" text-anchor="middle" font-family="Arial,sans-serif" font-weight="900" font-size="82" fill="'+fg+'">'+ini+'</text></svg>';
    return "data:image/svg+xml;charset=utf-8,"+encodeURIComponent(svg);
  };
  const fileData=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});
  const emptyState=()=>({
    tournaments:[],
    divisions:[],
    courts:[],
    clubs:[],
    players:[],
    teams:[],
    teamPlayers:{},
    matches:[],
    referees:[],
    registrations:[],
    sponsors:[],
    posts:[],
    branding:{name:"Pickle Tour",primaryColor:"#0a8b55",accentColor:"#dfff69",logoUrl:""},
    bookings:[],
    clubEvents:[],
    clubAttendance:{},
    clubTransactions:[],
    ratingHistory:{},
    audit:[]
  });
  let state=JSON.parse(localStorage.getItem(KEY)||"null")||emptyState();
  state.clubEvents||=[];state.clubAttendance||={};state.clubTransactions||=[];
  const avatarMigration=state.players?.some(p=>!p.avatar_url);
  if(avatarMigration){
    state.players.forEach(p=>{if(!p.avatar_url)p.avatar_url=svgAvatar(p.full_name||"Player")});
    localStorage.setItem(KEY,JSON.stringify(state));
  }
  const recomputeStats=()=>{
    const stats=new Map(state.teams.map(t=>[t.id,{w:0,l:0,sw:0,sl:0,pf:0,pa:0}]));
    const isGroupMatch=m=>!m.bracketSlot&&((m.stage&&m.stage.startsWith("Bảng"))||/bảng|group|vòng bảng/i.test(m.stage||"")||!/chung kết|bán kết|tứ kết/i.test(m.stage||""));
    for(const m of (state.matches||[]).filter(x=>(x.status==="done"||x.status==="completed")&&isGroupMatch(x)&&x.winner)){
      const ms=m.sets||[];let ap=0,bp=0,asw=0,bsw=0;
      for(const [a,b] of ms){
        ap+=Number(a||0);bp+=Number(b||0);
        if(Number(a)>Number(b))asw++;else if(Number(b)>Number(a))bsw++;
      }
      const sa=stats.get(m.a),sb=stats.get(m.b);
      if(sa){sa.pf+=ap;sa.pa+=bp;sa.sw+=asw;sa.sl+=bsw;m.winner===m.a?sa.w++:sa.l++}
      if(sb){sb.pf+=bp;sb.pa+=ap;sb.sw+=bsw;sb.sl+=asw;m.winner===m.b?sb.w++:sb.l++}
    }
    state.teams.forEach(t=>{
      const s=stats.get(t.id)||{w:0,l:0,sw:0,sl:0,pf:0,pa:0};
      Object.assign(t,{...s,diffSet:s.sw-s.sl,diffPts:s.pf-s.pa});
    });
  };
  recomputeStats();
  const persist=()=>{recomputeStats();localStorage.setItem(KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent("pickle-preview-update",{detail:clone(state)}));};
  const api={
    me:async()=>({user:{id:"local-admin",email:"",name:"Quản trị viên",role:"super_admin"}}),
    logout:async()=>({ok:true}),changePassword:async()=>({ok:true}),
    publicState:async()=>{recomputeStats();return clone(state)},
    submitTournament:async(payload)=>{const isFeatured=payload.sponsorPackage==="top_sponsor"||payload.sponsorPackage==="highlight";const t={id:"tour-"+Date.now(),name:payload.name,date:payload.startAt?new Date(payload.startAt).toLocaleDateString("vi-VN"):"Sắp diễn ra",startAt:payload.startAt,endAt:payload.endAt,venue:payload.venue,format:payload.divisionName||"Open",status:"open",publicVisible:true,teams:0,isFeatured,featuredRank:payload.sponsorPackage==="top_sponsor"?100:50,sponsorPackage:payload.sponsorPackage||"free"};state.tournaments.unshift(t);persist();return {success:true,tournament:t};},
    adminState:async()=>{recomputeStats();return clone(state)},
    publicPlayers:async()=>clone(state.players.map(p=>({...p,club_city:state.clubs.find(c=>c.id===p.club_id)?.city||""}))),
    publicClubs:async()=>clone(state.clubs),
    publicPosts:async()=>clone(state.posts.filter(x=>x.status==="published")),
    publicSponsors:async()=>clone(state.sponsors),
    publicBranding:async()=>clone(state.branding),
    publicCheckin:async token=>{const r=state.registrations.find(x=>x.id===token);if(!r)throw Object.assign(new Error("NOT_FOUND"),{status:404});return clone({...r,start_at:new Date().toISOString()})},
    confirmCheckin:async token=>{const r=state.registrations.find(x=>x.id===token);if(!r)throw Object.assign(new Error("NOT_FOUND"),{status:404});r.checked_in_at=new Date().toISOString();persist();return clone(r)},
    publicPlayer:async id=>{
      const p=state.players.find(x=>x.id===id);if(!p)throw Object.assign(new Error("NOT_FOUND"),{status:404});
      const myTeams=Object.entries(state.teamPlayers).filter(([,ids])=>ids.includes(id)).map(([tid])=>tid);
      const matches=state.matches.filter(m=>myTeams.includes(m.a)||myTeams.includes(m.b)).map(m=>{
        const myTeam=myTeams.includes(m.a)?m.a:m.b,side=myTeam===m.a?"A":"B";
        let myPoints=0,oppPoints=0;(m.sets||[]).forEach(s=>{if(side==="A"){myPoints+=s[0];oppPoints+=s[1]}else{myPoints+=s[1];oppPoints+=s[0]}});
        const team=state.teams.find(t=>t.id===myTeam),division=state.divisions.find(d=>d.id===team?.divisionId),tournament=state.tournaments.find(t=>t.id===division?.tournamentId);return {id:m.id,tournamentId:tournament?.id||null,tournamentName:tournament?.name||"",divisionName:division?.name||"",stage:m.stage,status:m.status,teamAName:state.teams.find(t=>t.id===m.a)?.name||"TBD",teamBName:state.teams.find(t=>t.id===m.b)?.name||"TBD",mySide:side,winnerTeamId:m.winner,won:m.status==="done"&&m.winner===myTeam,lost:m.status==="done"&&m.winner&&m.winner!==myTeam,sets:m.sets||[],myPoints,oppPoints};
      });
      const wins=matches.filter(x=>x.won).length,losses=matches.filter(x=>x.lost).length,pf=matches.reduce((a,x)=>a+x.myPoints,0),pa=matches.reduce((a,x)=>a+x.oppPoints,0);
      const partnerIds=[...new Set(myTeams.flatMap(tid=>state.teamPlayers[tid]||[]).filter(pid=>pid!==id))];
      return {profile:{id:p.id,fullName:p.full_name,nickname:p.nickname,gender:p.gender,rating:p.rating,avatarUrl:p.avatar_url,clubName:p.club_name,clubCity:"TP.HCM"},stats:{wins,losses,matches:wins+losses,winRate:wins+losses?Math.round(wins*1000/(wins+losses))/10:0,pointsFor:pf,pointsAgainst:pa,diff:pf-pa},teams:myTeams.map(tid=>{const team=state.teams.find(t=>t.id===tid),division=state.divisions.find(d=>d.id===team?.divisionId),tournament=state.tournaments.find(t=>t.id===division?.tournamentId);return {id:tid,tournament_id:tournament?.id||null,tournament_name:tournament?.name||"",division_name:division?.name||"",start_at:tournament?.startAt||null}}),partners:partnerIds.map(pid=>{const x=state.players.find(p=>p.id===pid);return {id:x.id,full_name:x.full_name,avatar_url:x.avatar_url,rating:x.rating,club_name:x.club_name}}),matches,ratingHistory:clone(state.ratingHistory[id]||[])};
    },
    players:async()=>clone(state.players),clubs:async()=>clone(state.clubs),
    importPlayers:async rows=>{let created=0;const playerMap=new Map(state.players.map(x=>[x.full_name.toLowerCase(),x])),clubMap=new Map(state.clubs.map(c=>[c.name.toLowerCase(),c]));for(const r of rows){const name=String(r.fullName||r.name||"").trim();if(!name)continue;const avatar=String(r.avatarUrl||r.avatar_url||r.avatar||"").trim(),lName=name.toLowerCase();let p=playerMap.get(lName);if(p){if(avatar)p.avatar_url=avatar;created++;continue;}const cName=String(r.club||"").trim();let club=cName?clubMap.get(cName.toLowerCase()):null;if(!club&&cName){club={id:uid(),name:cName,city:"",active:true};state.clubs.push(club);clubMap.set(cName.toLowerCase(),club)}const newP={id:uid(),full_name:name,nickname:r.nickname||"",gender:["male","female","other"].includes(r.gender)?r.gender:null,rating:Number(r.rating)||3,phone:r.phone||"",club_id:club?.id||null,club_name:club?.name||"Tự do",active:true,avatar_url:avatar||svgAvatar(name)};state.players.push(newP);playerMap.set(lName,newP);created++}persist();return {created}},
    importTeams:async(did,rows)=>{let created=0,linkedPlayers=0;for(const r of rows){const name=String(r.name||"").trim();if(!name)continue;let club=state.clubs.find(c=>c.name.toLowerCase()===String(r.club||"").trim().toLowerCase());if(!club&&r.club){club={id:uid(),name:r.club,city:"",active:true};state.clubs.push(club)}const id=uid(),t={id,divisionId:did,name,club:club?.name||"Tự do",clubId:club?.id||null,group:r.group||"A",seed:Number(r.seed)||null,status:"active",w:0,l:0,pf:0,pa:0};state.teams.push(t);state.teamPlayers[id]=[];for(const pn of [r.player1,r.player2,r.player3,r.player4].filter(Boolean)){let p=state.players.find(x=>x.full_name.toLowerCase()===String(pn).trim().toLowerCase());if(!p){p={id:uid(),full_name:String(pn).trim(),nickname:"",gender:null,rating:3,club_id:club?.id||null,club_name:club?.name||"Tự do",active:true,avatar_url:svgAvatar(String(pn).trim())};state.players.push(p)}state.teamPlayers[id].push(p.id);linkedPlayers++}created++}persist();return {created,linkedPlayers}},
    uploadReceipt:async file=>({url:await fileData(file)}),
    uploadImage:async file=>({url:await fileData(file)}),
    uploadPlayerAvatar:async(id,file)=>{const x=state.players.find(v=>v.id===id);x.avatar_url=await fileData(file);persist();return {avatarUrl:x.avatar_url}},
    createClub:async p=>{const x={id:uid(),name:p.name,city:p.city||"",active:true};state.clubs.push(x);persist();return clone(x)},
    updateClub:async(id,p)=>{const x=state.clubs.find(v=>v.id===id);Object.assign(x,p);state.players.filter(v=>v.club_id===id).forEach(v=>v.club_name=x.name);persist();return clone(x)},
    deleteClub:async id=>{const x=state.clubs.find(v=>v.id===id);const used=state.players.some(v=>v.club_id===id)||state.teams.some(t=>t.clubId===id);if(used){x.active=false;persist();return {mode:"archived",entity:clone(x)}}state.clubs=state.clubs.filter(v=>v.id!==id);persist();return {mode:"deleted"}},
    createPlayer:async p=>{const club=state.clubs.find(c=>c.id===p.clubId);const x={id:uid(),full_name:p.fullName,nickname:p.nickname||"",gender:p.gender||null,rating:Number(p.rating||3),phone:p.phone||"",club_id:p.clubId||null,club_name:club?.name||"Tự do",active:true,avatar_url:svgAvatar(p.fullName||"P")};state.players.push(x);persist();return clone(x)},
    updatePlayer:async(id,p)=>{const x=state.players.find(v=>v.id===id);const club=state.clubs.find(c=>c.id===p.clubId);Object.assign(x,{full_name:p.fullName??x.full_name,nickname:p.nickname??x.nickname,gender:p.gender??x.gender,phone:p.phone??x.phone,club_id:p.clubId===undefined?x.club_id:(p.clubId||null),club_name:p.clubId===undefined?x.club_name:(club?.name||"Tự do"),active:p.active??x.active});persist();return clone(x)},
    deactivatePlayer:async id=>{const x=state.players.find(v=>v.id===id);x.active=false;persist();return {mode:"deactivated",entity:clone(x)}},
    adjustRating:async(id,p)=>{const x=state.players.find(v=>v.id===id),before=Number(x.rating||0);x.rating=Math.max(0,before+Number(p.delta||0));(state.ratingHistory[id]||(state.ratingHistory[id]=[])).unshift({before_rating:before,delta:Number(p.delta||0),after_rating:x.rating,reason:p.reason||"",created_at:new Date().toISOString()});persist();return clone(x)},
    createTournament:async p=>{const t={id:uid(),name:p.name,date:p.startAt?new Date(p.startAt).toLocaleDateString("vi-VN"):"Chưa chốt",startAt:p.startAt||null,endAt:null,venue:p.venue||"Chưa chốt",format:"Tournament",status:"open",publicVisible:true,teams:0};state.tournaments.push(t);const d={id:uid(),tournamentId:t.id,name:"Open",eventType:p.eventType||"doubles",format:"pool_to_knockout",bestOf:3,pointsToWin:11,winByTwo:true,advanceCount:2,active:true};state.divisions.push(d);persist();return {tournament:t,division:d}},
    updateTournament:async(id,p)=>{const x=state.tournaments.find(v=>v.id===id);Object.assign(x,{name:p.name??x.name,venue:p.venue??x.venue,startAt:p.startAt??x.startAt,endAt:p.endAt??x.endAt,status:p.status==="registration"?"open":(p.status??x.status),publicVisible:p.publicVisible??x.publicVisible});if(p.startAt)x.date=new Date(p.startAt).toLocaleDateString("vi-VN");persist();return clone(x)},
    deleteTournament:async id=>{const x=state.tournaments.find(v=>v.id===id);const dids=state.divisions.filter(d=>d.tournamentId===id).map(d=>d.id);const hasHistory=state.matches.some(m=>dids.includes(m.divisionId))||state.registrations.some(r=>dids.some(did=>state.divisions.find(d=>d.id===did)?.name===r.division_name));if(hasHistory){x.status="cancelled";x.publicVisible=false;persist();return {mode:"archived",entity:clone(x)}}state.tournaments=state.tournaments.filter(v=>v.id!==id);state.divisions=state.divisions.filter(d=>d.tournamentId!==id);persist();return {mode:"deleted"}},
    createDivision:async(tid,p)=>{const d={id:uid(),tournamentId:tid,name:p.name,eventType:p.eventType,format:p.format,bestOf:p.bestOf,pointsToWin:p.pointsToWin,winByTwo:p.winByTwo,advanceCount:p.advanceCount,active:true};state.divisions.push(d);persist();return clone(d)},
    updateDivisionFull:async(id,p)=>{const d=state.divisions.find(x=>x.id===id);Object.assign(d,p);persist();return clone(d)},
    deleteDivision:async id=>{const d=state.divisions.find(x=>x.id===id);const used=state.matches.some(m=>m.divisionId===id)||state.teams.some(t=>t.divisionId===id);if(used){d.active=false;persist();return {mode:"archived",entity:clone(d)}}state.divisions=state.divisions.filter(x=>x.id!==id);persist();return {mode:"deleted"}},
    createCourt:async(tid,p)=>{const x={id:uid(),tournamentId:tid,name:p.name,sortOrder:state.courts.filter(c=>c.tournamentId===tid).length+1,active:true};state.courts.push(x);persist();return clone(x)},
    updateCourt:async(id,p)=>{Object.assign(state.courts.find(x=>x.id===id),p);persist();return {}},
    deleteCourt:async id=>{const x=state.courts.find(c=>c.id===id);const used=state.matches.some(m=>m.courtId===id)||state.bookings.some(b=>b.court_id===id);if(used){x.active=false;persist();return {mode:"archived",entity:clone(x)}}state.courts=state.courts.filter(c=>c.id!==id);persist();return {mode:"deleted"}},
    createTeam:async(did,p)=>{const id=uid();const club=state.clubs.find(c=>c.id===p.clubId);const t={id,divisionId:did,name:p.name,club:club?.name||p.club||"Tự do",clubId:p.clubId||club?.id||null,group:p.group||"A",seed:p.seed||null,status:"active",w:0,l:0,pf:0,pa:0};state.teams.push(t);state.teamPlayers[id]=[];persist();return clone(t)},
    updateTeam:async(id,p)=>{const t=state.teams.find(x=>x.id===id);const club=state.clubs.find(c=>c.id===p.clubId);Object.assign(t,{name:p.name??t.name,clubId:p.clubId===undefined?t.clubId:(p.clubId||null),club:p.clubId===undefined?t.club:(club?.name||"Tự do"),group:p.group??t.group,seed:p.seed??t.seed,status:p.status??t.status});persist();return clone(t)},
    deleteTeam:async id=>{const t=state.teams.find(x=>x.id===id);const used=state.matches.some(m=>m.a===id||m.b===id)||state.registrations.some(r=>r.team_name===t?.name);if(used){t.status="withdrawn";persist();return {mode:"withdrawn",entity:clone(t)}}state.teams=state.teams.filter(x=>x.id!==id);delete state.teamPlayers[id];persist();return {mode:"deleted"}},
    updateDivision:async(id,p)=>{Object.assign(state.divisions.find(x=>x.id===id),p);persist();return {}},
    createMatch:async(did,p)=>{const court=state.courts.find(c=>c.id===p.courtId);const m={id:uid(),divisionId:did,stage:p.stage||"Vòng bảng",court:court?.sortOrder||court?.name||"—",courtId:p.courtId||null,time:p.scheduledAt?new Date(p.scheduledAt).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"}):"—",a:p.teamAId,b:p.teamBId,status:"wait",sets:[],current:[0,0],winner:null,version:1,refereeId:p.refereeUserId||null};state.matches.push(m);persist();return clone(m)},
    autoSeedGroups:async(did,groupCount)=>{const teams=state.teams.filter(t=>t.divisionId===did&&t.status!=="withdrawn").map(t=>{const ps=(state.teamPlayers[t.id]||[]).map(id=>state.players.find(p=>p.id===id)).filter(Boolean);return {...t,avg:ps.length?ps.reduce((a,p)=>a+Number(p.rating||0),0)/ps.length:0}}).sort((a,b)=>b.avg-a.avg||(a.seed||999)-(b.seed||999));if(teams.length<groupCount)throw new Error("MORE_GROUPS_THAN_TEAMS");const groups=Array.from({length:groupCount},(_,i)=>({label:String.fromCharCode(65+i),teams:[]}));const max=Math.ceil(teams.length/groupCount);teams.forEach((t,i)=>{const cycle=Math.floor(i/groupCount),pos=i%groupCount,pref=cycle%2===0?pos:groupCount-1-pos;const choices=[pref,...groups.map((_,j)=>j).filter(j=>j!==pref)].filter(j=>groups[j].teams.length<max).sort((a,b)=>{const as=t.clubId&&groups[a].teams.some(x=>x.clubId===t.clubId)?1:0,bs=t.clubId&&groups[b].teams.some(x=>x.clubId===t.clubId)?1:0;return as-bs||groups[a].teams.length-groups[b].teams.length});const g=groups[choices[0]??pref];g.teams.push(t);const real=state.teams.find(x=>x.id===t.id);real.group=g.label;real.seed=i+1});persist();return {groupCount,assignments:clone(groups)}},
    generateRoundRobin:async did=>{const teams=state.teams.filter(t=>t.divisionId===did&&t.status!=="withdrawn");const groups=[...new Set(teams.map(t=>t.group).filter(Boolean))];let created=0;for(const g of groups){const arr=teams.filter(t=>t.group===g);for(let i=0;i<arr.length;i++)for(let j=i+1;j<arr.length;j++){if(state.matches.some(m=>m.divisionId===did&&((m.a===arr[i].id&&m.b===arr[j].id)||(m.a===arr[j].id&&m.b===arr[i].id))))continue;const court=state.courts[created%Math.max(1,state.courts.length)];state.matches.push({id:uid(),divisionId:did,stage:"Bảng "+g,court:court?.sortOrder||1,courtId:court?.id||null,time:"--:--",a:arr[i].id,b:arr[j].id,status:"wait",sets:[],current:[0,0],winner:null,version:1,bracketSlot:null});created++}}persist();return {created}},
    generateBracket:async did=>{const d=state.divisions.find(x=>x.id===did);if(!d)throw new Error("NOT_FOUND");if(state.matches.some(m=>m.divisionId===did&&m.bracketSlot))throw new Error("BRACKET_ALREADY_EXISTS");const teams=state.teams.filter(t=>t.divisionId===did&&t.status!=="withdrawn").sort((a,b)=>(a.seed||999)-(b.seed||999));if(teams.length<2)throw new Error("NOT_ENOUGH_QUALIFIERS");if(d.format==="double_elimination"&&![4,8].includes(teams.length))throw new Error("DOUBLE_ELIM_SUPPORTS_4_OR_8_TEAMS");if(d.format==="round_robin")throw new Error("ROUND_ROBIN_HAS_NO_KNOCKOUT");if(d.format==="double_elimination"){const order=teams.length===4?[teams[0],teams[3],teams[1],teams[2]]:[teams[0],teams[7],teams[3],teams[4],teams[1],teams[6],teams[2],teams[5]];const add=(stage,slot,a=null,b=null)=>{const m={id:uid(),divisionId:did,stage,bracketSlot:slot,court:1,courtId:state.courts[0]?.id||null,time:"--:--",a:a?.id||a||"TBD",b:b?.id||b||"TBD",status:"wait",sets:[],current:[0,0],winner:null,version:1};state.matches.push(m);return m};if(teams.length===4){add("Nhánh thắng - Vòng 1","DE-W-R1-M1",order[0],order[1]);add("Nhánh thắng - Vòng 1","DE-W-R1-M2",order[2],order[3]);add("Nhánh thắng - Chung kết","DE-W-F");add("Nhánh thua - Vòng 1","DE-L-R1-M1");add("Nhánh thua - Chung kết","DE-L-F");add("Chung kết tổng","DE-GF");persist();return {format:"double_elimination",created:6}}for(let i=0;i<4;i++)add("Nhánh thắng - Tứ kết","DE-W-QF-M"+(i+1),order[i*2],order[i*2+1]);add("Nhánh thắng - Bán kết 1","DE-W-SF-M1");add("Nhánh thắng - Bán kết 2","DE-W-SF-M2");add("Nhánh thắng - Chung kết","DE-W-F");add("Nhánh thua - Vòng 1","DE-L-R1-M1");add("Nhánh thua - Vòng 1","DE-L-R1-M2");add("Nhánh thua - Vòng 2","DE-L-R2-M1");add("Nhánh thua - Vòng 2","DE-L-R2-M2");add("Nhánh thua - Bán kết","DE-L-SF");add("Nhánh thua - Chung kết","DE-L-F");add("Chung kết tổng","DE-GF");persist();return {format:"double_elimination",created:14}}let size=2;while(size<teams.length)size*=2;let order=[1,2];for(let n=4;n<=size;n*=2){const next=[];for(const seed of order)next.push(seed,n+1-seed);order=next}const slots=order.map(n=>teams[n-1]||null),rounds=Math.log2(size);let created=0;for(let r=0;r<rounds;r++){const count=size/(2**(r+1));for(let i=0;i<count;i++){const a=r===0?slots[i*2]:null,b=r===0?slots[i*2+1]:null;state.matches.push({id:uid(),divisionId:did,stage:count===1?"Chung kết":count===2?"Bán kết "+(i+1):count===4?"Tứ kết "+(i+1):"Knockout R"+(r+1)+" - Trận "+(i+1),bracketSlot:"SE-R"+(r+1)+"-M"+(i+1),court:1,courtId:state.courts[0]?.id||null,time:"--:--",a:a?.id||"TBD",b:b?.id||"TBD",status:(a&&!b)||(!a&&b)?"done":"wait",sets:[],current:[0,0],winner:(a&&!b)?a.id:(!a&&b?b.id:null),resultReason:(a&&!b)||(!a&&b)?"bye":null,version:1});created++}}persist();return {format:d.format,bracketSize:size,created}},

    assignMatch:async(id,p)=>{const m=state.matches.find(x=>x.id===id);if(p.courtId!==undefined){const ct=p.courtId?state.courts.find(x=>x.id===p.courtId):null;m.courtId=p.courtId||null;m.court=ct?.sortOrder||ct?.name||"—"}if(p.refereeUserId!==undefined)m.refereeId=p.refereeUserId||null;if(p.scheduledAt!==undefined)m.time=p.scheduledAt?new Date(p.scheduledAt).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"}):"—";m.version++;persist();return clone(m)},
    updateMatch:async(id,p)=>{const m=state.matches.find(x=>x.id===id);Object.assign(m,p);if(p.scheduledAt)m.time=new Date(p.scheduledAt).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"});m.version++;persist();return clone(m)},
    deleteMatch:async id=>{const m=state.matches.find(x=>x.id===id);if(m.status==="done")throw Object.assign(new Error("COMPLETED_MATCH_LOCKED"),{status:409});if(m.status==="wait"&&!m.sets.length&&!(m.current?.[0]||m.current?.[1])){state.matches=state.matches.filter(x=>x.id!==id);persist();return {mode:"deleted"}}m.status="cancelled";persist();return {mode:"cancelled",entity:clone(m)}},
    point:async(id,p)=>{const m=state.matches.find(x=>x.id===id),i=p.side==="A"?0:1;m.current[i]=Math.max(0,m.current[i]+Number(p.delta));m.status="live";m.version++;persist();return clone(m)},
    finishSet:async id=>{const m=state.matches.find(x=>x.id===id);m.sets.push([...m.current]);m.current=[0,0];m.version++;persist();return clone(m)},
    finishMatch:async id=>{const m=state.matches.find(x=>x.id===id);const aw=m.sets.filter(s=>s[0]>s[1]).length,bw=m.sets.filter(s=>s[1]>s[0]).length;m.winner=aw>=bw?m.a:m.b;m.status="done";m.version++;persist();return clone(m)},
    quickScore:async(id,p)=>{const m=state.matches.find(x=>x.id===id);if(!m)throw new Error("NOT_FOUND");const rawSets=Array.isArray(p.sets)?p.sets:[];m.sets=rawSets.map(s=>[Number(s[0]||0),Number(s[1]||0)]).filter(([a,b])=>a>0||b>0);m.current=[0,0];let aw=0,bw=0;m.sets.forEach(([a,b])=>{if(a>b)aw++;else if(b>a)bw++});m.winner=aw>=bw?m.a:m.b;m.status="done";m.version++;persist();return clone(m)},
    specialResult:async(id,p)=>{const m=state.matches.find(x=>x.id===id);m.winner=p.winnerTeamId;m.status="done";m.resultReason=p.reason;m.resultNote=p.note||"";m.version++;persist();return clone(m)},
    undo:async id=>{const m=state.matches.find(x=>x.id===id);if(m.current[0]||m.current[1]){if(m.current[0]>=m.current[1]&&m.current[0]>0)m.current[0]--;else if(m.current[1]>0)m.current[1]--}m.version++;persist();return clone(m)},
    referees:async()=>clone(state.referees),createReferee:async p=>{const r={id:uid(),email:p.email,display_name:p.name,active:true};state.referees.push(r);persist();return clone(r)},updateReferee:async(id,p)=>{const r=state.referees.find(x=>x.id===id);if(!r)throw new Error("NOT_FOUND");Object.assign(r,{display_name:p.name??r.display_name,email:p.email??r.email,active:p.active??r.active});persist();return clone(r)},
    registrations:async()=>clone(state.registrations),
    createRegistration:async(did,p)=>{const d=state.divisions.find(x=>x.id===did),t=state.tournaments.find(x=>x.id===d?.tournamentId),team=state.teams.find(x=>x.id===p.teamId);const r={id:uid(),status:"approved",payment_status:"unpaid",amount:p.amount||null,team_name:team?.name||"",division_name:d?.name||"",tournament_name:t?.name||"",checked_in_at:null,payment_id:null,payment_review_status:null};state.registrations.push(r);persist();return clone(r)},
    updateRegistration:async(id,p)=>{const r=state.registrations.find(x=>x.id===id);Object.assign(r,{status:p.status??r.status,payment_status:p.paymentStatus??r.payment_status,amount:p.amount??r.amount});persist();return clone(r)},
    deleteRegistration:async id=>{const r=state.registrations.find(x=>x.id===id);if(r.checked_in_at||r.payment_id){r.status="cancelled";persist();return {mode:"cancelled",entity:clone(r)}}state.registrations=state.registrations.filter(x=>x.id!==id);persist();return {mode:"deleted"}},
    checkin:async id=>{const r=state.registrations.find(x=>x.id===id);r.checked_in_at=new Date().toISOString();persist();return clone(r)},
    undoCheckin:async id=>{const r=state.registrations.find(x=>x.id===id);r.checked_in_at=null;persist();return clone(r)},
    checkinQr:async id=>{const data='<svg xmlns="http://www.w3.org/2000/svg" width="420" height="420"><rect width="420" height="420" fill="white"/><rect x="45" y="45" width="330" height="330" rx="22" fill="#0d2118"/><text x="210" y="200" fill="#dfff69" font-size="58" font-family="Arial" font-weight="900" text-anchor="middle">QR</text><text x="210" y="250" fill="white" font-size="18" font-family="Arial" text-anchor="middle">'+id+'</text></svg>';return {token:id,url:location.href.split("/preview/")[0]+"/preview/checkin.html?token="+id,dataUrl:"data:image/svg+xml;charset=utf-8,"+encodeURIComponent(data)}},
    addPayment:async(id,p)=>{const r=state.registrations.find(x=>x.id===id);r.payment_id=uid();r.payment_review_status="pending";r.payment_status="pending";persist();return clone(r)},
    reviewPayment:async(pid,status)=>{const r=state.registrations.find(x=>x.payment_id===pid);if(r){r.payment_review_status=status;r.payment_status=status==="approved"?"paid":"unpaid";persist()}return clone(r)},
    sponsors:async()=>clone(state.sponsors),createSponsor:async p=>{const x={id:uid(),name:p.name,tier:p.tier,logo_url:p.logoUrl||null,website_url:p.websiteUrl||"",sort_order:state.sponsors.length+1};state.sponsors.push(x);persist();return clone(x)},updateSponsor:async(id,p)=>{Object.assign(state.sponsors.find(x=>x.id===id),p);persist();return {}},deleteSponsor:async id=>{state.sponsors=state.sponsors.filter(x=>x.id!==id);persist();return {ok:true}},
    posts:async()=>clone(state.posts),createPost:async p=>{const x={id:uid(),title:p.title,slug:uid(),excerpt:p.excerpt||"",body:p.body||"",cover_url:p.coverUrl||null,status:p.status||"draft",published_at:p.status==="published"?new Date().toISOString():null};state.posts.unshift(x);persist();return clone(x)},updatePost:async(id,p)=>{const x=state.posts.find(v=>v.id===id);Object.assign(x,p);if(p.status==="published"&&!x.published_at)x.published_at=new Date().toISOString();persist();return clone(x)},deletePost:async id=>{state.posts=state.posts.filter(x=>x.id!==id);persist();return {ok:true}},
    branding:async()=>clone(state.branding),saveBranding:async p=>{state.branding={...state.branding,...p};persist();return clone(state.branding)},
    clubEvents:async()=>clone(state.clubEvents.map(e=>{const a=state.clubAttendance[e.id]||[];return {...e,club_name:state.clubs.find(c=>c.id===e.club_id)?.name||"",participants:a.filter(x=>x.status!=="cancelled").length,attended:a.filter(x=>x.status==="attended").length}}).sort((a,b)=>new Date(a.start_at)-new Date(b.start_at))),
    createClubEvent:async p=>{const x={id:uid(),club_id:p.clubId,title:p.title,event_type:p.eventType||"social",venue:p.venue||"",start_at:p.startAt,end_at:p.endAt||null,max_participants:p.maxParticipants||null,fee:Number(p.fee)||0,status:"scheduled"};state.clubEvents.push(x);state.clubAttendance[x.id]=[];persist();return clone(x)},
    updateClubEvent:async(id,p)=>{const x=state.clubEvents.find(v=>v.id===id);Object.assign(x,{title:p.title??x.title,event_type:p.eventType??x.event_type,venue:p.venue??x.venue,start_at:p.startAt??x.start_at,end_at:p.endAt===undefined?x.end_at:p.endAt,max_participants:p.maxParticipants??x.max_participants,fee:p.fee??x.fee,status:p.status??x.status});persist();return clone(x)},
    deleteClubEvent:async id=>{const x=state.clubEvents.find(v=>v.id===id);x.status="cancelled";persist();return {mode:"cancelled",entity:clone(x)}},
    clubAttendance:async eventId=>clone((state.clubAttendance[eventId]||[]).map(a=>{const p=state.players.find(x=>x.id===a.player_id)||{};return {...a,full_name:p.full_name||"",nickname:p.nickname||"",avatar_url:p.avatar_url||null,rating:p.rating||0}})),
    addClubAttendance:async(eventId,playerId)=>{const arr=state.clubAttendance[eventId]||(state.clubAttendance[eventId]=[]);let x=arr.find(v=>v.player_id===playerId);if(x){x.status="registered";x.checked_in_at=null}else{x={event_id:eventId,player_id:playerId,status:"registered",checked_in_at:null};arr.push(x)}persist();return clone(x)},
    updateClubAttendance:async(eventId,playerId,status)=>{const x=(state.clubAttendance[eventId]||[]).find(v=>v.player_id===playerId);if(!x)throw new Error("NOT_FOUND");x.status=status;x.checked_in_at=status==="attended"?new Date().toISOString():null;persist();return clone(x)},
    clubTransactions:async()=>clone(state.clubTransactions.map(x=>({...x,club_name:state.clubs.find(c=>c.id===x.club_id)?.name||"",created_by_name:"Quản trị viên"})).sort((a,b)=>new Date(b.occurred_at)-new Date(a.occurred_at))),
    createClubTransaction:async p=>{const x={id:uid(),club_id:p.clubId,direction:p.direction,category:p.category||"other",amount:Number(p.amount)||0,note:p.note||"",occurred_at:p.occurredAt||new Date().toISOString(),created_by_name:"Quản trị viên"};state.clubTransactions.unshift(x);persist();return clone(x)},
    bookings:async()=>clone(state.bookings),createBooking:async p=>{const court=state.courts.find(c=>c.id===p.courtId),tournament=state.tournaments.find(t=>t.id===court?.tournamentId);const x={id:uid(),court_id:p.courtId,court_name:court?.name||"Sân",tournament_name:tournament?.name||"",title:p.title,contact_name:p.contactName,contact_phone:p.contactPhone,start_at:p.startAt,end_at:p.endAt,status:"confirmed",notes:p.notes};state.bookings.unshift(x);persist();return clone(x)},updateBooking:async(id,p)=>{Object.assign(state.bookings.find(x=>x.id===id),p);persist();return {}},deleteBooking:async id=>{const x=state.bookings.find(v=>v.id===id);x.status="cancelled";persist();return {mode:"cancelled",entity:clone(x)}},
    reportOverview:async()=>{const income=state.clubTransactions.filter(x=>x.direction==="income").reduce((a,x)=>a+Number(x.amount||0),0),expense=state.clubTransactions.filter(x=>x.direction==="expense").reduce((a,x)=>a+Number(x.amount||0),0),today=new Date().toDateString();return {players:state.players.filter(p=>p.active!==false).length,members:state.players.filter(p=>p.active!==false).length,registrations:state.registrations.length,checked_in:state.registrations.filter(r=>r.checked_in_at).length,paid_count:state.registrations.filter(r=>r.payment_status==="paid").length,revenue:state.registrations.filter(r=>r.payment_status==="paid").reduce((a,r)=>a+Number(r.amount||0),0),matches:state.matches.length,live:state.matches.filter(m=>m.status==="live").length,completed:state.matches.filter(m=>m.status==="done").length,attendanceToday:Object.values(state.clubAttendance).flat().filter(a=>a.status==="attended"&&a.checked_in_at&&new Date(a.checked_in_at).toDateString()===today).length,upcomingActivities:state.clubEvents.filter(e=>e.status!=="cancelled"&&new Date(e.start_at)>=new Date()).length,clubIncome:income,clubExpense:expense,clubBalance:income-expense}},
    addTeamPlayer:async(teamId,playerId)=>{const team=state.teams.find(t=>t.id===teamId),player=state.players.find(p=>p.id===playerId);if(!team||!player)throw new Error("NOT_FOUND");const arr=state.teamPlayers[teamId]||(state.teamPlayers[teamId]=[]);if(!arr.includes(playerId))arr.push(playerId);persist();return {ok:true}}
  };
  window.PickleAPI=api;
  window.io=()=>({on:(event,cb)=>window.addEventListener("pickle-preview-update",e=>{if(event==="public:state"||event==="match:update")cb(clone(e.detail))})});
  window.addEventListener("storage",e=>{if(e.key===KEY&&e.newValue){state=JSON.parse(e.newValue);window.dispatchEvent(new CustomEvent("pickle-preview-update",{detail:clone(state)}))}});
})();